default: styles/vael.scss
# vael-alt-v3: styles/vael-alt.scss
# vael-v3: styles/vael_old.scss
mastodon-dark: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss